### ISSUE TITLE
console error, missing function

### ISSUE THREAD

**Issue by raymond301** [noypi/npWidgets#1]
Trying to use: np-img-enlarger.min.js
I followed the setup steps, base image appears, but not the enlargement.

Uncaught TypeError: b.$applyAsync is not a function

I think I figured this out.
I'm using : AngularJS v1.2.16
You are using : v1.3.0
$applyAsync doesn't work. But if I change the method to $eval, I can retain the same functionality in an older version of Angular.

Perhaps you can just make a note about version compatibility on your website tutorial.

**Comment by noypi** [comment]
Thanks.
